export interface Branch {
  active: number;
  address: null;
  city_id: number;
  created_at: string;
  deleted_at: null;
  email: string;
  id: number;
  is_clients: number;
  is_mangers: number;
  is_papers: number;
  is_projects: number;
  is_services: number;
  is_shifts: number;
  latitude: string;
  longitude: string;
  manager_id: number;
  name: string;
  parent_id: null;
  phone: string;
  polygon: null;
  share_client: number;
  share_manager: number;
  share_paper: number;
  share_service: number;
  share_shift: number;
  shift_id: number;
  type: string;
  updated_at:string;
}
