export interface Contract {
    "id": number,
    "code": string,
    "period": string,
    "date": string,
    "card_image": string,
    "details": string,
    "type": string,
    "amount": number,
    "contract_type_id": number,
    "client_id": number,
    "branch_id": number,
    "management_id": number,
    "status_id": number,
    "employee_id": number,
}
